In [1]:
pip install numpy


In [15]:
import numpy as np
#Khởi tạo một mảng numpy nguyên a (1-D) với n phần tử ngẫu nhiên trong khoảng từ [1, 14]
n = int(input())
a = np.random.randint(1,15,n)
print(a)
print("dim: ", a.ndim, " ,shape: ", a.shape, " ,len: ",len(a), " ,itemsize: ",a.itemsize, " ,dtype: ",a.dtype)
print()

#Khởi tạo 1 mảng numpy b với 100 số chẵn đầu tiên.
b = np.arange(0,200,2)
print(b)
print("dim: ", b.ndim, " ,shape: ", b.shape, " ,len: ",len(b), " ,itemsize: ",b.itemsize, " ,dtype: ",b.dtype)
print()

#Khởi tạo 1 ma trận numpy c có kích thước nxn với 100 phần tử 0, in ra màn hình.
c = np.zeros((10,10))
print(c)
print("dim: ", c.ndim, " ,shape: ", c.shape, " ,len: ",len(c), " ,itemsize: ",c.itemsize, " ,dtype: ",c.dtype)
print()

#Khởi tạo ma trận đơn vị d có kích thước nxn.
d= np.eye(n)
print(d)
print("dim: ", d.ndim, " ,shape: ", d.shape, " ,len: ",len(d), " ,itemsize: ",d.itemsize, " ,dtype: ",d.dtype)
print()

#Khởi tạo ma trận đường chéo e với các giá trị trên đường chéo là mảng a.
e=np.diag(a)
print(e)
print("dim: ", e.ndim, " ,shape: ", e.shape, " ,len: ",len(e), " ,itemsize: ",e.itemsize, " ,dtype: ",e.dtype)






10
[13 10 13  7  4 13  7  1  1  7]
dim:  1  ,shape:  (10,)  ,len:  10  ,itemsize:  8  ,dtype:  int64

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]
dim:  1  ,shape:  (100,)  ,len:  100  ,itemsize:  8  ,dtype:  int64

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
dim:  2  ,shape:  (10, 10)  ,len:  10  ,itemsize:  8  ,dtype:  float64

[[1. 0. 0. 0. 0. 0.