In [1]:
pip install numpy


In [7]:
import numpy as np
n = int(input())
a = np.array([int(input())for i in range(n)])
b = np.array([int(input())for i in range(n)])

# In ra max, min, giá trị trung bình, độ lệch chuẩn của vector, giá trị trung vị
print(f"max of array a = {np.max(a)}")
print(f"min of array a = {np.min(a)}")
print(f"mean of array a = {np.mean(a)}")
print(f"standard of array a = {np.std(a)} ")
print(f"median of array a = {np.median(a)}")
print()
print(f"max of array b = {np.max(b)}")
print(f"min of array b = {np.min(b)}")
print(f"mean of array b = {np.mean(b)}")
print(f"standard of array b = {np.std(b)} ")
print(f"median of array b = {np.median(b)}")

#Tạo 1 ma trận numpy c (2-D) có kích thước nx2 từ a, b, in ra màn hình.
c = np.array([a,b]).T
print(c)
print()

#Khởi tạo 1 ma trận (2-D) numpy d với kích thước nxn theo phân phối Gauss (với mean, std của b), in kết quả ra màn hình.
meanB = np.mean(b)
stdB = np.std(b)
d = np.random.normal(meanB,stdB,(n,n))
print(d)
print()

# Tính tổng, hiệu, tích 2 ma trận, tích ma trận chuyển vị của d với ma trận nghịch đảo của d
print(f"sum = {a+b}")
print(f"sub = {a-b}")
print(f"mul1  = {a * b}10")
print(f"mul2 = {np.dot(d.T,np.linalg.inv(d))}")
print()

#Chuyển ma trận c về tensor numpy e (3-D) (nếu không đủ dữ liệu để chuyển về 3-D thì thêm dữ liệu), in ra màn hình.
e = np.expand_dims(c,axis = 0)
print(e)





4
2
5
10
5
2
90
5
3
max of array a = 10
min of array a = 2
mean of array a = 5.5
standard of array a = 2.8722813232690143 
median of array a = 5.0

max of array b = 90
min of array b = 2
mean of array b = 25.0
standard of array b = 37.54330832518626 
median of array b = 4.0
[[ 2  2]
 [ 5 90]
 [10  5]
 [ 5  3]]

[[ 1.97108971e+01  6.05523983e+01 -1.76318317e+01  2.68004873e-02]
 [-9.38169216e+00  1.67576594e+01 -6.97111785e+00  4.57941483e+01]
 [ 1.93419781e+01  4.00640119e+01 -2.04101273e+01 -4.16256669e+01]
 [-1.96362035e+00  4.48418105e+01  4.23978360e+01  3.66661490e+01]]

sum = [ 4 95 15  8]
sub = [  0 -85   5   2]
mul1  = [  4 450  50  15]10
mul2 = [[ 2.64743343 -2.48785947 -2.91129633 -0.25336226]
 [ 8.77946516 -6.60511453 -9.10889182 -0.8749647 ]
 [-0.59892762  1.52479501  0.40967454 -0.28254468]
 [ 0.12693652  1.66231487  0.64319092 -0.34604931]]

[[[ 2  2]
  [ 5 90]
  [10  5]
  [ 5  3]]]
