In [1]:
pip install numpy


In [20]:
import numpy as np
# Lập 1 mảng 2 chiều lưu lần lượt điểm đại số tuyến tính, xác suất thống kê, giải tích với 20 phần tử mỗi hàng random trong khoảng từ [0, 10].
a = np.random.randint(0,10,(3,20))
print(a)
print()
#In ra giá vị trí điểm lớn nhất và nhỏ nhất ở mỗi môn.
print(f"index of max = {np.argmax(a)}")
print(f"index of min = {np.argmin(a)}")
print()

#Làm phẳng mảng và xóa đi các vị trí có điểm là 0, in ra màn hình.
b = a.flatten()[a.flatten() != 0]
print(b)
print()
#Sắp xếp giảm theo thuật toán quicksort, in ra màn hình.
c = np.sort(b)[::-1]
print(c)
print()
#
k = int(input("nhap k: "))
insert_pos = np.searchsorted(b,k,side = 'right')
d = np.insert(b,insert_pos,k)
print(d)







[[1 4 4 8 5 2 0 4 6 8 1 1 0 7 0 1 2 5 1 2]
 [0 3 3 9 8 8 7 6 8 1 3 6 6 7 5 8 2 9 4 1]
 [9 3 0 8 4 1 9 1 7 9 4 1 4 9 9 3 0 7 4 9]]

index of max = 23
index of min = 6

[1 4 4 8 5 2 4 6 8 1 1 7 1 2 5 1 2 3 3 9 8 8 7 6 8 1 3 6 6 7 5 8 2 9 4 1 9
 3 8 4 1 9 1 7 9 4 1 4 9 9 3 7 4 9]

[9 9 9 9 9 9 9 9 8 8 8 8 8 8 8 7 7 7 7 7 6 6 6 6 5 5 5 4 4 4 4 4 4 4 4 3 3
 3 3 3 2 2 2 2 1 1 1 1 1 1 1 1 1 1]

nhap k: 4
[1 4 4 8 5 2 4 6 8 1 1 7 1 2 5 1 2 3 3 4 9 8 8 7 6 8 1 3 6 6 7 5 8 2 9 4 1
 9 3 8 4 1 9 1 7 9 4 1 4 9 9 3 7 4 9]
